test:
  stage: test
  image: golang
  before_script:
    - mkdir -p $GOPATH/src/gitlab.com/$CI_PROJECT_NAMESPACE
    - cd $GOPATH/src/gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - go get ./...
    - go build -v
    - go test -cover -bench=.
  after_script:
    - go get github.com/alecthomas/gometalinter
    - gometalinter --install
    - go get github.com/gojp/goreportcard/cmd/goreportcard-cli
    - goreportcard-cli -v

deploy:
  stage: deploy
  image: google/cloud-sdk
  before_script:
    - echo $DEPLOY_KEY_FILE > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  script:
    - gcloud functions deploy time
      --runtime go111 --trigger-http --project bryton
      --memory 128 --timeout 10 --entry-point entryPoint
